### ISSUE TITLE
Support for push_manifest.json

### ISSUE THREAD

**Issue by JosefJezek** [pixelcodeUK/polymer-static-analyze#1]
Could you add option for generate `push_manifest.json`? I need this option for PWA Template on GAE.
- https://github.com/GoogleChrome/http2-push-manifest
- https://github.com/GoogleChrome/http2push-gae
- https://github.com/StartPolymer/progressive-web-app-template

Thank you

**Comment by pixelcodeUK** [comment]
Added a CLI option and a new function to produce the push_manifest.json file :)

**Comment by JosefJezek** [comment]
Thank you... I'm going to test
